image: python: 3.7

stages:
  - test
  - deploy

tests:
  stage: test
  script:
    - python3 -m pip3 install -r requirements.txt
    - python -m unittest -v tests/tests.py

development:
  type: deploy
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=task-o-bot-test --api-key=$HEROKU_API_KEY
  only:
  - develop

production:
  type: deploy
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=task-o-bot --api-key=$HEROKU_API_KEY
  only:
  - master